# A minimal example of how to configure this module

municipal_benchmark: 36.5
internal_use_factor: 0.7
include_desal: True
include_ZLD: False
basic_withdrawal_cost: 0.01 # unit: EUR/m3
freshwater_for_h2: 0.5 # proportion of usable water allocated for green hydrogen production
compensate: True
plot_limit: 1 # unit: 1e9 m3
# countries:
#   - ALB
#   - ARE
#   - AUT
#   - LVA
#   - SRB
#   - BOL
